#!/usr/bin/env sh
set -eu

city="${GC_CITY:-/home/jjgarzella/Developer/ai/city/math-city}"
kaimon_root="$city/.gc/kaimon-canary"
gate_src="$kaimon_root/julia_depot/packages/KaimonGate/YvD3m"
kaimon_project="$kaimon_root/project"
julia_bin="${JULIA:-/home/jjgarzella/.juliaup/bin/julia}"

export JULIA_LOAD_PATH="@:@v#.#:@stdlib:$gate_src:$kaimon_project"
export JULIA_PKG_PRECOMPILE_AUTO=0
exec "$julia_bin" "$@"
